CREATE TABLE public.roles (
	id int4 NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT roles_pk PRIMARY KEY (id)
);

CREATE TABLE public.tenants (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT tenants_pk PRIMARY KEY (id)
);

CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	tenant_id int4 NOT NULL,
	email varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	role_id int4 NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_email_un UNIQUE (email),
	CONSTRAINT users_tenants_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id),
	CONSTRAINT users_roles_fk FOREIGN KEY (role_id) REFERENCES roles(id)
);
CREATE INDEX users_tenant_id_idx ON public.users (tenant_id);
CREATE INDEX users_email_idx ON public.users (email);

INSERT INTO public.tenants
(id, created_by, created_date, last_modified_by, last_modified_date, "name")
VALUES(0, NULL, NULL, NULL, NULL, 'Super tenant administrator');

INSERT INTO public.roles
(id, "name")
VALUES(0, 'ROLE_SUPER_ADMIN');
INSERT INTO public.roles
(id, "name")
VALUES(1, 'ROLE_ADMIN');
INSERT INTO public.roles
(id, "name")
VALUES(2, 'ROLE_USER');

INSERT INTO public.users
(id, created_by, created_date, last_modified_by, last_modified_date, tenant_id, email, "name", "password", role_id)
VALUES(0, NULL, NULL, NULL, NULL, 0, 'super.admin@demo.com', 'Super admin', '$2a$10$i5ZlL2s3Gk4A2VCtkWKaJOzqYe0NfRQrq1emNbK/AHDsfdnPX/dfG', 0);